### ISSUE TITLE
[README] Broken link to image

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery-operator#147]
**Description**
This repo's readme.md has a broken link to the first image.

**Expected Behavior**
The image that should be displayed can be found here - https://github.com/layer5io/meshery-operator/tree/master/img/readme

**Comment by DineshKoushik** [comment]
Hi @leecalcote , Can I take over this issue?

**Comment by leecalcote** [comment]
That would be excellent, @DineshKoushik. Thank you.

**Comment by DineshKoushik** [comment]
@leecalcote Hi again, if you can tell me which out of the five image do I need to replace with, in the place of broken image?

**Comment by leecalcote** [comment]
Oh, I see that the image is missing in that folder. You can take a copy from here - https://github.com/meshery/meshery

https://raw.githubusercontent.com/meshery/meshery/master/.github/assets/images/meshery/meshery-tag-white-bg.png

**Comment by DineshKoushik** [comment]
@leecalcote I have updated the image, but seems like my create pull request button is disabled, may I know any solution for that?

**Comment by leecalcote** [comment]
Fork the repo, clone your fork, make changes, push to your fork, create pull request from your fork.

See CONTRIBUTING.md <https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md>

**Comment by DineshKoushik** [comment]
![image](https://user-images.githubusercontent.com/54497410/112494693-444fc500-8da9-11eb-9557-1e13fb2beb72.png)

I have done the same process you have mentioned above, but strangely the create pull request button is disabled.

**Comment by leecalcote** [comment]
Enter a value into the title?

**Comment by leecalcote** [comment]
While I'm helping you, @DineshKoushik, I have an ask - will you star the repos here - https://github.com/meshery?

**Comment by leecalcote** [comment]
@DineshKoushik little help in return?

**Comment by DineshKoushik** [comment]
@leecalcote I was thinking of staring the repos anyway, I just want some more help from you for my open source journey.

**Comment by leecalcote** [comment]
I highly recommend that you join the Meshery Community, if you're looking to grow in your open source journey. There's no community more welcoming to newcomers.

**Comment by DineshKoushik** [comment]
@leecalcote  I do not have any account with the domain name specified, to join meshery slack.
