### ISSUE TITLE
Meshery Operator errors incomprehensible

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery-operator#163]
**Description**
MeshSync is connected to Meshery Server, but a ping produces this error.

**Screenshots**
<img width="806" alt="Screen Shot 2021-05-24 at 9 47 54 PM" src="https://user-images.githubusercontent.com/7570704/119432363-da389b00-bcd9-11eb-8aaa-e1facb5599e9.png">

**Environment:**
 - Version: v0.5.15

---
[Optional] **To Reproduce**

[Optional] **Additional Context**

**Comment by leecalcote** [comment]
I'm still getting this error on Meshery v0.5.17

**Comment by leecalcote** [comment]
This needs a proper error code.

**Comment by leecalcote** [comment]
I'm running the edge release of Meshery and am still seeing these errors.

**Comment by leecalcote** [comment]
@kumarabd please address these defect soon. It carries a high priority label to help ensure that the Meshery Operator flows are smooth.

**Comment by kumarabd** [comment]
Tracking in meshery as this is an issue from meshery.
