### ISSUE TITLE
[README] Need to fix badges

### ISSUE THREAD

**Issue by amino19** [layer5io/meshery-operator#172]
**Description**

<a href="https://github.com/layer5io/meshery-operator/blob/master/README.md">README.md</a> is the first file one should read when starting a new project. For attractive look, we added some badges also.
But, there's a Slack badge failing, need to fix that. Plus, align all the badges to `center`
 
### Screenshot

**Current Behavior**

![image](https://user-images.githubusercontent.com/75872316/122453352-e3124900-cfc7-11eb-9ea0-f413e3880935.png)

**Desired Behavior**
All badges need to be fix in desired location as `center` + Slack badge as mention in reference below.
Refer : meshery <a href="https://github.com/layer5io/meshery/blob/master/README.md"> README.md </a>

**Environment:**
 - OS: any [e.g. Ubuntu]
 - Browser: any [e.g. Chrome, Safari]
 - Version: any [e.g. 22]
 - Device: any [e.g. laptop, iPhone 8]

**Comment by adithyaakrishna** [comment]
Assigning Myself on this 😶
