### ISSUE TITLE
[Build] Add GitHub Workflow for CI

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery-operator#5]
This repo will contain a Kubernetes Operator based on the Operator SDK using Golang.

Docker Repo: https://hub.docker.com/repository/docker/layer5/meshery-operator

**Comment by crustyy** [comment]
@leecalcote  can i work on this issue??

**Comment by nitishm** [comment]
Not sure what needs to be done here. @leecalcote should know.

**Comment by MukulMaheshwari** [comment]
@leecalcote  Can u please elaborate what needs to be done here ?

**Comment by leecalcote** [comment]
Yes, the go program needs to be compiled, linted, error checked, have static analysis checked... using the same methodology we use in building other Golang programs - https://github.com/meshery/meshery/blob/master/.github/workflows/ci.yml.

A docker image needs built and pushed to the repo listed above.

**Comment by subhamkrai** [comment]
@leecalcote I would like to take this up  if available :) . Thanks!

**Comment by leecalcote** [comment]
@subhamkrai do you worst. ;)

**Comment by subhamkrai** [comment]
I'll try my best to not make it worst.
