### ISSUE TITLE
Separate Meshery Operator and MeshSync

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery-operator#88]
**Tasks**
- [ ] separate code
- [ ] update CI workflow to accommodate

**Comment by kushthedude** [comment]
If I am not wrong the `pkg` directory contains meshsync code & informers right? @kalradev

**Comment by Aisuko** [comment]
@leecalcote Is task one was finished by @kalradev ?
https://github.com/meshery/meshsync/commit/1a1d5dff736470aad65f8b5ed6ada66e289fdd83#diff-e0ce1a7f3f76d7bfda0ffdae6e0226aa63b3009c4c4a770c321876aecad0a6c1

**Comment by 0xfirefist** [comment]
Code has been added to the Meshsync repo. But we have to remove it from this package. 
@kumarabd, where should these files go? 
- https://github.com/meshery/meshery-operator/blob/master/pkg/meshsync/controller.go
- https://github.com/meshery/meshery-operator/blob/master/pkg/broker/nats/controller.go

**Comment by 0xfirefist** [comment]
https://github.com/meshery/meshery-operator/pull/97 - It is solved with this PR. Closing this issue.
