### ISSUE TITLE
Change go mod project name

### ISSUE THREAD

**Issue by nitishm** [layer5io/meshery-operator#9]
The project is incorrectly named meshery-controller. The github.com/layer5io/ prefix was missed. 
Also maybe meshery-controller is not the best name. Any suggestions for a better name @AdheipSingh @vinayakshnd @leecalcote

**Comment by nitishm** [comment]
There is this small task if you are interested @crustyy . I can provide more details on slack if you are interested

**Comment by crustyy** [comment]
@nitishm yes sir ,i will take this issue😊
