### ISSUE TITLE
[Helm charts]: meshery-operator needs helm chart

### ISSUE THREAD

**Issue by Aisuko** [layer5io/meshery-operator#90]
**Current Behavior**

**Desired Behavior**

Meshery-operator needs helm charts:

* Can deploy into Kubernetes cluster by Helm chart.
* The chart is needsed to be included in the Meshery helm chart repo.

---
**Resources**

**Alternatives / Additional Context**

**Comment by Aisuko** [comment]
We need a stable image of meshoperator.

**Comment by leecalcote** [comment]
It turns out that we don't need this as Meshery deploys the Operator itself.
